baseURL = 'https://omarizquierdo.dev/'
languageCode = 'en-us'
title = 'Omar Izquierdo'
theme = 'poison'

[params]
    brand = "Omar Izquierdo"                      # name of your site - appears in the sidebar
    # remote_brand_image = 'https://github.com/USERNAME.png' # path to a remote file
    brand_image = "https://media.licdn.com/dms/image/D4D03AQHbXfXTDe9rGQ/profile-displayphoto-shrink_800_800/0/1684527493544?e=1706745600&v=beta&t=ql7vJErbJKZOvVuC-9ZefkpxRgQIvZ3lIkyxKOqRIsc"    # path to the image shown in the sidebar
    description = "Software Developer" # Used as default meta description if not specified in front matter
    dark_mode = false                      # optional - defaults to false
    favicon = "themes/poison/images/favicon-32x32.png"             # path to favicon (defaults to favicon.png)

    menu = [
        {Name = "About", URL = "/about/", HasChildren = false},
        {Name = "Posts", URL = "/posts/", Pre = "Recent", HasChildren = true, Limit = 5},
    ]


    github_url = "httpsL//github.com/SharkiCS"
    linkedin_url = "https://www.linkedin.com/in/%F0%9F%90%BC-omar-i-97531b263/"
    #tryhackme_url = "https://tryhackme.com"
    twitter_url = "https://twitter.com"
